image: node:latest
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@14.2.7
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - main
    - pages