stages:
  - dependencies
  - build

install_dependencies:
  image: node:19-alpine
  stage: dependencies
  script:
    - npm install
  only:
    - master
  cache:
    paths:
      - node_modules/

build_site:
  image: node:19-alpine
  stage: build
  script:
    - ng build
  artifacts:
    paths:
      - public/
  cache:
    paths:
      - node_modules/
