stages:
  - install_dependencies
  - build_site

install_dependencies:
  image: node:19-alpine
  stage: install_dependencies
  script:
    - npm install
  only:
    - master
  cache:
    paths:
      - node_modules/

build_site:
  image: node:19-alpine
  stage: build_site
  script:
    - ng build
  artifacts:
    paths:
      - public/
  cache:
    paths:
      - node_modules/
