image: node:latest
build-site:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@14.2.7
    - npm install
    - ng build --base-href /payroll-frontend/
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    - main

