image: node:19-alpine
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@14.2.7
    - npm install
    - ng build
    - mkdir public
    - cp -r /dist/payroll-frontend/. /public
  artifacts:
    paths:
      - public
  only:
    - main
    - pages