image: node:latest
build-site:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@14.2.7
    - npm install
    - ng build
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    - main

